"""add profile photo in users table

Revision ID: c584eaf8575f
Revises: 47946b048d2a
Create Date: 2025-02-26 11:49:29.202823

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c584eaf8575f"
down_revision: Union[str, None] = "47946b048d2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("profile_photo_key", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_photo_key")
    # ### end Alembic commands ###
