name: Web App
on:
  push:
    branches: "**"
  #   paths:
  #     - "**/*.ts"
  #     - "**/*.tsx"
  # pull_request:
  #   paths:
  #     - "**/*.ts"
  #     - "**/*.tsx"

env:
  NODE_VERSION: "20.x"

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ./webapp
        run: npm ci

      - name: Lint Check (ESLint)
        working-directory: ./webapp
        run: npm run lint

      - name: Format Check (Prettier)
        working-directory: ./webapp
        run: npm run format:check

      - name: Type Check
        working-directory: ./webapp
        run: npm run type-check
